### PR TITLE
Edits pass through 01_MC_NVT; added references

### PR DESCRIPTION
**Pull request by jchodera**
This is already great, but I've taken an edits pass and flagged a few instances where we will need to make some alterations---notably the addition of a smooth switching function.

### CODE REVIEW

**Comment by jchodera** [comment]
I can add the switching function changes if we're OK with adding that to the MC part.

Next up is the integrators in `02_MD_NVE.tex`, but I think it will be easier to have them actually do NVT instead of NVE (which opens up a can of worms we don't want to deal with).

**Comment by emarinri** [comment]
Sure, adding the switching function sounds good to me!

**Comment by jchodera** [comment]
> Sure, adding the switching function sounds good to me!

Thanks! Should I do that?

**Comment by emarinri** [comment]
Might be easier if you add it, if you're ok with that!

**Comment by jchodera** [comment]
On it!

**Pull request merged**
