### PR TITLE
Overhaul 02_MD_NVE.tex assignment

### PR DESCRIPTION
**Pull request by jchodera**
@emarinri : It looks like you didn't catch my slack messages that I was overhauling the `02_MD_NVE.tex` handout last night until now---sorry about that!

I've reworked the whole document to switch from NVE (which is fraught with problems) to NVT using a simple Langevin integrator (which is going to be much more useful for them, eliminates the need for removing center-of-mass velocities, etc). I've also added concrete tasks for them to carry out at the bottom of the document.

I merged in the additions I could from your changes, but some of the material was cut out because it was no longer relevant to the NVT assignment. Be sure to look over the PDF [here](https://github.com/dgasmith/MM_SSS_Lesson_Plan/blob/72d3285e6b181101b66978cec3e922eb682bb3eb/handouts/02_MD_NVE.pdf) before merging.

I'm about to hop on a plane, so I'll be able to catch up with this as soon as I land. I'm happy to make the code changes tonight---it should just be a few lines of code.

### CODE REVIEW

**Comment by jchodera** [comment]
I should also note that the introduction of the switching function was a bit tricky, so it would be great if someone could quickly check over the derivation of the forces!

**Comment by emarinri** [comment]
This is great! Thanks! I'll go over the derivation of the force!

**Comment by jchodera** [comment]
Thanks! I just caught some typos/issues with the derivatives and pushed the corrections before your comment so make sure to update if you haven't already.

**Comment by jchodera** [comment]
@emarinri: I've fixed the typos you caught and added the scalar switch function and its scalar derivative, but when I was trying to add a nosetest, it looks like the `test_LJ.py` might be out of sync with the API for `ForceField.py` since `params` is no longer used. I'm not quite sure how `ForceField` is supposed to receive the `sigma` and `epsilon` arguments in its current state:
```
lski1962:MM_SSS_Lesson_Plan.dgasmith choderaj$ nosetests -vv --nocapture test/test_LJ.py 
nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
test_LJ.test_lj ... ERROR
Test that switch function has correct limits. ... ERROR

======================================================================
ERROR: test_LJ.test_lj
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/choderaj/miniconda3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/choderaj/github/molssi/MM_SSS_Lesson_Plan/MM_SSS_Lesson_Plan.dgasmith/test/test_LJ.py", line 12, in test_lj
    lj_ff = mmpy.LennardJones(params, cutoff)
  File "/Users/choderaj/github/molssi/MM_SSS_Lesson_Plan/MM_SSS_Lesson_Plan.dgasmith/mm_python/ForceField.py", line 59, in __init__
    ForceField.__init__(self, "lennardJones", cutoff, switch)
  File "/Users/choderaj/github/molssi/MM_SSS_Lesson_Plan/MM_SSS_Lesson_Plan.dgasmith/mm_python/ForceField.py", line 35, in __init__
    if (switch > cutoff):
TypeError: unorderable types: float() > tuple()

======================================================================
ERROR: Test that switch function has correct limits.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/choderaj/miniconda3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/choderaj/github/molssi/MM_SSS_Lesson_Plan/MM_SSS_Lesson_Plan.dgasmith/test/test_LJ.py", line 33, in test_switch
    lj_ff = mmpy.LennardJones(params, cutoff, switch=switch)
NameError: name 'params' is not defined

----------------------------------------------------------------------
Ran 2 tests in 0.003s
```

**Comment by emarinri** [comment]
You're right. I just updated the tests so they're consistent with the reduced units implementation. Note I didn't touch the switch test.

**Comment by jchodera** [comment]
Awesome! I've just fixed the switch test.

All tests pass now:
```
lski1962:MM_SSS_Lesson_Plan.dgasmith choderaj$ nosetests -vv --nocapture test
nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
test_LJ.test_lj ... ok
Test that switch function has correct limits. ... ok
test_force.test_force ... ok
test_nistEnergy.test_nistEnergy ... ok

----------------------------------------------------------------------
Ran 4 tests in 12.202s

OK
```

**Pull request merged**
